### ISSUE TITLE
Error on "go get -u github.com/slok/go-http-metrics"

### ISSUE THREAD

**Issue by AleF83** [slok/go-http-metrics#20]
I get an error while trying to install the package.

```bash
go get -u github.com/slok/go-http-metrics
```

causes the following error:

```
go: finding github.com/golang/lint latest
go: github.com/golang/lint@v0.0.0-20190409202823-959b441ac422: parsing go.mod: unexpected module path "golang.org/x/lint"
go: finding github.com/streadway/amqp latest
go get: error loading module requirements
```

It seems to be related to [this issue](https://github.com/golang/lint/issues/455)

**Comment by slok** [comment]
Hi @AleF83!

Thanks for opening the issue.

I can't reproduce the problem that you are pointing:

```
$ docker run --rm -it  golang:1.12 go get -v -u github.com/slok/go-http-metrics
github.com/slok/go-http-metrics (download)
github.com/slok/go-http-metrics/metrics
github.com/slok/go-http-metrics/middleware
github.com/slok/go-http-metrics
```

What is the Go version you are using?

**Comment by AleF83** [comment]
Hey,
Thanks for answer.
I'm running this command not in Docker but on my Mac (Mojave).
```bash
go version
# go version go1.12.6 darwin/amd64
```
Running this in Docker works for me too.

**Comment by Gerifield** [comment]
I tried it on my Mac (Mojave 10.14.5) with go1.12.7 and it works fine for me.

**Comment by slok** [comment]
Hi @AleF83!

I can't reproduce the error and didn't fine anyone having the same issue, also knowing that it works with docker I'll assume that the problem is related with your go installation/configuration or stale dependencies in the `GOPATH` and not the library dependencies itself.

On go1.13 it works also ok.

I'll close the issue, if you need it open again or create a new one!
