### ISSUE TITLE
panic: duplicate metrics collector registration attempted (in tests)

### ISSUE THREAD

**Issue by aclowkey** [slok/go-http-metrics#45]
I'm running this middleware in my tests, that spawn multiple servers and it causes the following panic:

> panic: duplicate metrics collector registration attempted [recovered]
>         panic: duplicate metrics collector registration attempted
> 
> goroutine 251 [running]:
> testing.tRunner.func1.1(0x4b3ba20, 0xc0007ae8c0)
>         /usr/local/Cellar/go/1.15.2/libexec/src/testing/testing.go:1076 +0x30d
> testing.tRunner.func1(0xc000daa300)
>         /usr/local/Cellar/go/1.15.2/libexec/src/testing/testing.go:1079 +0x41a
> panic(0x4b3ba20, 0xc0007ae8c0)
>         /usr/local/Cellar/go/1.15.2/libexec/src/runtime/panic.go:969 +0x175
> github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc000292e10, 0xc000a7d440, 0x3, 0x3)
>         /Users/achaplianka/Dvelop/Prometheus/k-api/vendor/github.com/prometheus/client_golang/prometheus/registry.go:400 +0xad
> github.com/slok/go-http-metrics/metrics/prometheus.NewRecorder(0x0, 0x0, 0x521f440, 0xb, 0xb, 0xc000e35400, 0x8, 0x8, 0x4d2b3e0, 0xc000292e10, ...)
>

**Comment by slok** [comment]
Hi @aclowkey 

This is because you are using different metrics recorder with the same prometheus Registry. 

So, on the middleware creation, it will register the metrics on the prometheus registry and after the first time, prometheus, will panic.

You have 2 options:

- A single middleware and pass it to all the servers (create once and use on all servers).
- One middleware and prometheus registry for each server, Check [Registry](https://pkg.go.dev/github.com/slok/go-http-metrics@v0.9.0/metrics/prometheus#Config).

**Comment by aclowkey** [comment]
Thanks!
